### ISSUE TITLE
Brave support?

### ISSUE THREAD

**Issue by Aileana87** [AprilSylph/Filtering-Plus#2]
Hey, I was just wondering if you'd ever make this work in Brave browser? I switched from Chrome a while ago and assumed this would work in Brave since most chrome extensions do, but this does not, unfortunately.

**Comment by AprilSylph** [comment]
Brave doesn't have a mechanism for installing extensions other than from the Chrome Web Store. I assume it doesn't work because Brave doesn't have Manifest V3 support, but the Chrome Web Store has stopped accepting Manifest V2 submissions, making it impossible to add Brave support unless they opened their own extensions store.
